split into 2 compile jobs

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -2,12 +2,6 @@ name: OpenWrt-CI
 
 on:
   workflow_dispatch:
-    inputs:
-      enable_debug:
-        description: 'Enable Debug Session'
-        required: false
-        type: boolean
-        default: false
   schedule:
     - cron: '0 20 * * 0'
 
@@ -28,91 +22,66 @@ jobs:
           echo "latest=$(curl -s 'https://api.github.com/repos/immortalwrt/immortalwrt/commits/master' | jq -r '.sha' | cut -c1-7)" | tee -a $GITHUB_OUTPUT
           echo "release_tag=$(curl -s 'https://api.github.com/repos/immortalwrt/immortalwrt/tags' | jq -r '.[0].name')" | tee -a $GITHUB_OUTPUT
 
-  build_openwrt:
-    name: Build OpenWrt Firmware
+  build_toolchain:
+    name: Build Toolchain and Kernel
     runs-on: ubuntu-24.04
     needs: check_update
     if: needs.check_update.outputs.current != needs.check_update.outputs.latest || github.event_name == 'workflow_dispatch' || github.event_name == 'pull_request'
     env:
       TZ: Asia/Shanghai
     steps:
-      - name: Initialization environment
-        env:
-          DEBIAN_FRONTEND: noninteractive
-        run: |
-          sudo bash -c 'bash <(curl -s https://build-scripts.immortalwrt.org/init_build_environment.sh)'
-          sudo -E timedatectl set-timezone "Asia/Shanghai"
-          sudo -E apt-get -y autoremove --purge
-          sudo -E apt-get -y clean
-
-      - name: Maximize build space
-        uses: easimon/maximize-build-space@master
-        with:
-          root-reserve-mb: 8192
-          remove-dotnet: true
-          remove-android: true
-          remove-haskell: true
-          remove-codeql: true
-          remove-docker-images: true
-
-      - name: Checkout OpenWrt
-        uses: actions/checkout@v4
-        with:
-          repository: immortalwrt/immortalwrt
-
-      - name: Cache Toolchain
-        uses: klever1988/cachewrtbuild@main
-        with:
-          ccache: 'true'
-          toolchain: 'true'
-          mixkey: 'x86_64'
-
-      - name: Setup Debug Session
-        if: github.event.inputs.enable_debug == 'true'
-        uses: mxschmitt/action-tmate@v3
-
-      - name: Update feeds
-        run: |
-          sed -i '$a src-git smpackage https://github.com/kenzok8/small-package' feeds.conf.default
-          ./scripts/feeds update -a
-          rm -rf feeds/smpackage/{base-files,dnsmasq,firewall*,fullconenat,libnftnl,nftables,ppp,opkg,ucl,upx,vsftpd*,miniupnpd-iptables,wireless-regdb}
-          ./scripts/feeds install -a
-
-      - name: Download configuration file
+      - name: Checkout CI repository
         uses: actions/checkout@v4
         with:
           path: CI
-          
-      - name: Configure
-        run: |
-          cp CI/.config .
-          python3 CI/busybox.py package/utils/busybox/Config-defaults.in
-          export version=$(echo ${{ needs.check_update.outputs.release_tag }} | sed 's/v//')
-          cp .config .config.raw
-          echo "CONFIG_VERSION_NUMBER=\"$version\"" >> .config
-          echo "CONFIG_VERSION_REPO=\"https://github.com/$GITHUB_REPOSITORY/releases\"" >> .config
-          make defconfig
-          diff .config .config.raw | tee .config.diff || :
 
-      - name: Download packages
-        run: |
-          wget https://github.com/$GITHUB_REPOSITORY/raw/refs/heads/main/setmirrors.py
-          python3 setmirrors.py
-          make download V=s -j1
+      - name: Setup build environment
+        uses: ./CI/.github/actions/setup-build-environment
+        with:
+          release_tag: ${{ needs.check_update.outputs.release_tag }}
+          cache_key: toolchain-kernel
 
-      - name: Patch
+      - name: Compile toolchain and kernel
+        id: compile_toolchain
         run: |
-          if ! grep -q "CONFIG_X86_SGX" target/linux/x86/64/config-6.12; then
-            echo "# CONFIG_X86_SGX is not set" >> target/linux/x86/64/config-6.12
-          fi
-          export param=$(cat package/base-files/files/usr/lib/os-release | grep BUILD_DATE | sed 's/.*=//')
-          echo "BUILD_DATE=$param" >> package/base-files/files/usr/lib/os-release
-          cat > feeds/smpackage/luci-app-ota/root/etc/config/ota <<EOF
+          alias mkdir='mkdir -p'
+          make tools/compile toolchain/compile target/compile -j$(nproc) || echo "result=fail" >> $GITHUB_OUTPUT
 
-          config ota 'config'
-                  option api_url 'https://github.com/$GITHUB_REPOSITORY/releases/latest/download/fw.json'
-          EOF
-          sed -i 's/curl /curl -L /g' feeds/smpackage/luci-app-ota/root/bin/ota
+      - name: Compile toolchain and kernel(2)
+        id: compile_toolchain2
+        if: steps.compile_toolchain.outputs.result == 'fail'
+        run: |
+          make tools/compile toolchain/compile target/compile V=s -j1 || echo "result=fail" >> $GITHUB_OUTPUT
+
+      - name: Compile toolchain and kernel(3)
+        if: steps.compile_toolchain2.outputs.result == 'fail'
+        run: |
+          make tools/compile toolchain/compile target/compile V=s -j1
+
+      - name: Save cache
+        uses: ./CI/.github/actions/save-cache
+        with:
+          cache_key: toolchain-kernel
+          max_size_gb: '9'
+
+  build_openwrt:
+    name: Build OpenWrt Firmware
+    runs-on: ubuntu-24.04
+    needs: [check_update, build_toolchain]
+    if: needs.check_update.outputs.current != needs.check_update.outputs.latest || github.event_name == 'workflow_dispatch' || github.event_name == 'pull_request'
+    env:
+      TZ: Asia/Shanghai
+    steps:
+      - name: Checkout CI repository
+        uses: actions/checkout@v4
+        with:
+          path: CI
+
+      - name: Setup build environment
+        uses: ./CI/.github/actions/setup-build-environment
+        with:
+          release_tag: ${{ needs.check_update.outputs.release_tag }}
+          cache_key: toolchain-kernel
 
       - name: Compile OpenWrt
         id: compile1
@@ -135,6 +104,12 @@ jobs:
         run: |
           ls bin/targets/x86/64
           df -h
+
+      - name: Save cache
+        uses: ./CI/.github/actions/save-cache
+        with:
+          cache_key: toolchain-kernel
+          max_size_gb: '9'
 
       - name: Upload buildinfo
         uses: actions/upload-artifact@v4
